<?php

namespace Tests\Browser;

use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Chrome;
use Tests\DuskTestCase;

class ExampleTest extends DuskTestCase
{
    use DatabaseMigrations;

    /**
     * A basic browser test example.
     *
     * @return void
     */

    public static function prepare()
    {
        parent::prepare(); // TODO: Change the autogenerated stub
        static::startChromeDriver();
    }

    public function testBasicExample()
    {
        $user = factory(User::class)->create([
            'email' => 'kururuygiroro@hotmail.com',
        ]);

        $this->browse(function ($browser) use ($user) {
            $browser->visit('/login')
                ->type('email', $user->email)
                ->type('password','password')
                ->press('Login')
                ->assertPathIs('/home');
        });
    }
}
